# Generated by Django 4.2.6 on 2024-03-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mob', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.IntegerField(null=True)),
                ('datecreated', models.DateTimeField(null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
