# Generated by Django 4.2.6 on 2024-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
