# Generated by Django 4.2.6 on 2024-03-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_person_caption_alter_person_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='caption',
        ),
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
