# Generated by Django 4.2.6 on 2024-03-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_person_caption_alter_person_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pic',
        ),
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(default='hi', upload_to='images/'),
        ),
    ]
