# Generated by Django 5.0.1 on 2024-03-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_person_pic_person_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='img',
        ),
    ]
